[[redirects]]
  from = "/lessons/*"
  to = "https://nicodann-drumlessons.netlify.app/lessons/:splat"
  status = 200
  force = true

  [[redirects]]
  from = "/lessons"
  to = "https://nicodann-drumlessons.netlify.app/lessons/"
  status = 200
  force = true